// src/app/layout.tsx
import React from "react";
import Navbar from "../../components/nav/page";
import Footer from "../../components/footer/page";

export const metadata = {
  title: "INFINITY MARINE CONSULTANTS",
  description: "Generated by Next.js",
};

// Add the following comment to mark this component as a client entry
// @use-client

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
