// src/app/layout.tsx
import React from "react";
import Navbar from "../../components/nav/page";
import Footer from "../../components/footer/page";
import { SpeedInsights } from "@vercel/speed-insights/next";
export const metadata = {
  title: "INFINITY MARINE CONSULTANTS",
  description: "Generated by Next.js",
};

// Add the following comment to mark this component as a client entry
// @use-client

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        {/* Add the link to your favicon.ico or favicon.png */}
        <link rel="icon" href="/logo.jpg" />
      </head>
      <body style={{ margin: 0 }}>
        <header>
          <Navbar />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
